name: "Create UPM Branch"
author: "hecomi"
description: "Create release branches for Unity Package Manager"
inputs:
    git-tag:
        description: "Tag name like v1.0.0"
        required: true
    main-branch:
        description: "Main branch name"
        required: false
        default: "main"
    upm-branch:
        description: "UPM branch name"
        required: false
        default: "upm"
    pkg-root-dir-path:
        description: "Root directory path that contains package.json"
        required: true
    samples-dir:
        description: "Directory name that contains samples"
        required: false
        default: "Samples"
    root-files:
        description: "File names that are imported from the main branch"
        required: false
        default: "README.md CHANGELOG.md LICENSE.md"
runs:
    using: "composite"
    steps:
        - run: ${{ github.action_path }}/create-upm-branches.sh
          shell: bash
          env:
              TAG: ${{ inputs.git-tag }}
              MAIN_BRANCH: ${{ inputs.main-branch }}
              UPM_BRANCH: ${{ inputs.upm-branch }}
              PKG_ROOT_DIR_PATH: ${{ inputs.pkg-root-dir-path }}
              SAMPLES_DIR: ${{ inputs.samples-dir }}
              ROOT_FILES: ${{ inputs.root-files }}
branding:
    icon: "package"
    color: "lightgreen"

